add active attribute to the GFS_typesdef.meta wherever needed
NOAA-EMC/ufsatm pull request #156
Opened 2020-08-10 22:28 UTC by XiaSun-NOAA

## Description
Add the active attribute to the vars wherever needed in the GFS_typesdef.meta file.
All the vars that are allocated in the GFS_typesdef.F90 based on `if `conditions were added an extra active attribute, except for `phy_fctd`.
In GFS_typesdef.F90: 
```
    if (Model%nctp > 0 .and. Model%cscnv) then
      allocate (Tbd%phy_fctd (IM,Model%nctp))
      Tbd%phy_fctd = clear_val
    endif
```
When 
`active = (number_of_cloud_types_CS > 0 .and. flag_for_Chikira_Sugiyama_deep_convection) `
is added to `phy_fctd `in GFS_typesdef.meta, error message is `'Exception: Variable number_of_cloud_types_cs used in conditional for cloud_base_mass_flux not known to host model`

Further inspection reveals that this is related to the upper case used in the active attribute. Somehow `items = FORTRAN_CONDITIONAL_REGEX.findall(var.active.lower())` in the ` mkstatic.py` only returns lower case strings. I have tried `items = FORTRAN_CONDITIONAL_REGEX.findall(var.active)`, then `print (items)`, they are still lower case string.

Currently, the active attribute needed for `phy_fctd ` is not included yet.

## Testing
All 57 regression tests passed on Hera using the intel compiler with the current updated GFS_typesdef.meta file

## Dependencies
n/a

2020-08-11 02:53 UTC, climbfuji requested changes
This is great work, @XiaSun-NOAA. I did a first pass through the entire file, and it looks pretty good to me. Only a few small changes, but please double check that my logic makes sense. Will need to do another pass one when it's our time to merge (there will be some updates to the variables in `GFS_typedefs.F90`, especially because of the recent RRTMGP commit).

2020-08-11 02:53 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  active = (number_of_chemical_tracers > 0)
Should this be
```
active = (number_of_chemical_tracers > 0 .and. number_of_dust_bins_for_diagnostics > 0)
```
?

2020-08-11 02:53 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  active = (number_of_chemical_tracers > 0)
Should this be
```
active = (number_of_chemical_tracers > 0 .and. number_of_seasalt_bins_for_diagnostics > 0)
```
?

2020-08-11 02:53 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  active = (index_for_first_chemical_tracer > 0 .and. number_of_chemical_tracers > 0)
I know the logic is confusing, but I think it suffices to say
```
active = (number_of_chemical_tracers_for_diagnostics > 0)
```

2020-08-11 02:53 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  active = (number_of_chemical_tracers > 0)
Reading it again, I think we can just say
```
active = (number_of_seasalt_bins_for_diagnostics > 0)
```

2020-08-11 02:53 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  active = (number_of_chemical_tracers > 0)
Reading it again, I think we can just say
```
active = (number_of_dust_bins_for_diagnostics > 0)
```

2020-08-11 02:53 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  active = (index_for_first_chemical_tracer > 0 .and. number_of_chemical_tracers > 0)
Same as for `sedim`.

2020-08-11 02:53 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  active = (index_for_first_chemical_tracer > 0 .and. number_of_chemical_tracers > 0)
Same as for `sedim`.

2020-08-11 02:53 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  active = (index_for_first_chemical_tracer > 0 .and. number_of_chemical_tracers > 0)
Same as for `sedim`.

2020-08-11 20:33 UTC, XiaSun-NOAA commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  active = (number_of_chemical_tracers > 0)
Thank you @climbfuji, it makes sense. I have updated the file in the following commit.

2020-08-11 21:24 UTC, XiaSun-NOAA commented
Thank you @climbfuji . I have made corresponding modifications and will run the RT tests when it is time.

2020-08-11 21:26 UTC, climbfuji commented
Thanks very much for this, you'll need to pull in the updates from the authoritative repositories at that time, too. Probably look at what as changed in GFS_typedefs.F90 before/after the update from develop and see if anything needs to be changed in GFS_typedefs.meta.

2020-08-31 18:58 UTC, XiaSun-NOAA commented
@climbfuji Hi Dom, I included the recent changes of GFS_typedef.F90 into the meta file. RT tests are waiting in the queue and might take some time to start running. Thanks!

2020-09-01 06:53 UTC, XiaSun-NOAA commented
Recent land-surface perturbation changes are included in the GFS_typdefs.meta file.

2020-09-01 17:36 UTC, climbfuji commented
This PR was pulled into https://github.com/NOAA-EMC/fv3atm/pull/153 and the missing `active` attribute for `phy_fctd` was added (after making the necessary changes in ccpp-framework).

2020-09-02 19:26 UTC, climbfuji commented
@XiaSun-NOAA this was merged as part of https://github.com/NOAA-EMC/fv3atm/pull/153, please close the PR.

2020-09-02 19:29 UTC, closed without merging