Correct metadata name/unit/dimension
NOAA-EMC/ufsatm pull request #170
Opened 2020-09-10 15:35 UTC by mzhangw

This PR includes metadata name/unit/dimension correctness. It does not change answers.
The associated PR:https://github.com/NCAR/ccpp-physics/pull/496

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #<issue_number>
- fixes noaa-emc/fv3atm/issues/<issue_number>

## Testing

How were these changes tested?  
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- Please commit the regression test log files in your ufs-weather-model branch

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on noaa-emc/nems/pull/<pr_number>
- waiting on noaa-emc/fv3atm/pull/<pr_number>

2020-09-30 00:17 UTC, climbfuji commented
Note: this PR will be pulled into a feature branch feature/transition-to-capgen-1 in the NCAR GitHub repo, which collects several non-answer-changing PRs for that effort of transitioning to `cap_gen.py`.

2020-09-30 00:24 UTC, climbfuji requested changes
Same as for ccpp-physics, a number of changes need to be reverted, they don't belong into this PR and will cause conflicts later on when merging HWRF physics etc. Others are ok even though not within the scope of this PR.

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.F90
> +    character(len=20), pointer :: fscav_aero(:)   !< aerosol scavenging factors
As far as I can see, all changes to `GFS_typedefs.F90` need to be reverted.

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  standard_name = flag_for_cloud_overlapping_method_for_shortwave_radiation
Please revert this change.

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  standard_name = flag_for_cloud_overlapping_method_for_longwave_radiation
Please revert this change.

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  standard_name = flag_for_subcolumn_cloud_approximation_for_shortwave_radiation
Please revert this change.

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  standard_name = flag_for_subcolumn_cloud_approximation_for_longwave_radiation
Please revert this change.

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +[fscav_sas]
Please revert this change.

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  active = (flag_for_subcolumn_cloud_approximation_for_longwave_radiation == 2 .or. flag_for_subcolumn_cloud_approximation_for_shortwave_radiation == 2)
Please revert this change.

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  active = (flag_for_subcolumn_cloud_approximation_for_longwave_radiation == 2 .or. flag_for_subcolumn_cloud_approximation_for_shortwave_radiation == 2)
Please revert this change.

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  standard_name = ice_nucleation_number
Same as for ccpp-physics, has this change been coordinated with @grantfirl and @ligiabernardet?

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +  standard_name = tendency_of_ccn_activated_number
Same as for ccpp-physics, has this change been coordinated with @grantfirl and @ligiabernardet?

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> -[qv_r]
Please revert the changes between lines 6582 and 6629.

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> -[cwm]
Please revert this change.

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +[fscav_cs]
Please revert this change.

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +[pcldtausw]
Please revert this change.

2020-09-30 00:24 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +[pcldtaulw]
Please revert this change.

2020-09-30 14:51 UTC, mzhangw commented
I will do it today.


On Tue, Sep 29, 2020 at 6:24 PM Dom Heinzeller <notifications@github.com>
wrote:

> *@climbfuji* requested changes on this pull request.
>
> Same as for ccpp-physics, a number of changes need to be reverted, they
> don't belong into this PR and will cause conflicts later on when merging
> HWRF physics etc. Others are ok even though not within the scope of this PR.
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.F90
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497172129>:
>
> > @@ -1055,6 +1055,7 @@ real (kind=kind_phys), pointer :: prsik (:,:) => null()   !< Exner function at i
>  !--- tracer handling
>      character(len=32), pointer :: tracer_names(:) !< array of initialized tracers from dynamic core
>      integer              :: ntrac           !< number of tracers
> +    character(len=20), pointer :: fscav_aero(:)   !< aerosol scavenging factors
>
> As far as I can see, all changes to GFS_typedefs.F90 need to be reverted.
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497172886>:
>
> > @@ -2469,14 +2469,14 @@
>    dimensions = ()
>    type = integer
>  [iovr_sw]
> -  standard_name = flag_for_max_random_overlap_clouds_for_shortwave_radiation
> -  long_name = sw: max-random overlap clouds
> +  standard_name = flag_for_cloud_overlapping_method_for_shortwave_radiation
>
> Please revert this change.
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497172944>:
>
> >    units = flag
>    dimensions = ()
>    type = integer
>  [iovr_lw]
> -  standard_name = flag_for_max_random_overlap_clouds_for_longwave_radiation
> -  long_name = lw: max-random overlap clouds
> +  standard_name = flag_for_cloud_overlapping_method_for_longwave_radiation
>
> Please revert this change.
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173004>:
>
> > @@ -2487,14 +2487,14 @@
>    dimensions = ()
>    type = integer
>  [isubc_sw]
> -  standard_name = flag_for_sw_clouds_without_sub_grid_approximation
> -  long_name = flag for sw clouds without sub-grid approximation
> +  standard_name = flag_for_subcolumn_cloud_approximation_for_shortwave_radiation
>
> Please revert this change.
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173048>:
>
> >    units = flag
>    dimensions = ()
>    type = integer
>  [isubc_lw]
> -  standard_name = flag_for_lw_clouds_without_sub_grid_approximation
> -  long_name = flag for lw clouds without sub-grid approximation
> +  standard_name = flag_for_subcolumn_cloud_approximation_for_longwave_radiation
>
> Please revert this change.
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173242>:
>
> > @@ -4035,7 +4035,7 @@
>    units = flag
>    dimensions = (number_of_chemical_tracers)
>    type = logical
> -[fscav]
> +[fscav_sas]
>
> Please revert this change.
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173472>:
>
> > @@ -4572,14 +4572,14 @@
>    units = none
>    dimensions = (horizontal_dimension)
>    type = integer
> -  active = (flag_for_lw_clouds_without_sub_grid_approximation == 2 .or. flag_for_sw_clouds_without_sub_grid_approximation == 2)
> +  active = (flag_for_subcolumn_cloud_approximation_for_longwave_radiation == 2 .or. flag_for_subcolumn_cloud_approximation_for_shortwave_radiation == 2)
>
> Please revert this change.
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173505>:
>
> >  [icsdlw]
>    standard_name = seed_random_numbers_lw
>    long_name = random seeds for sub-column cloud generators lw
>    units = none
>    dimensions = (horizontal_dimension)
>    type = integer
> -  active = (flag_for_lw_clouds_without_sub_grid_approximation == 2 .or. flag_for_sw_clouds_without_sub_grid_approximation == 2)
> +  active = (flag_for_subcolumn_cloud_approximation_for_longwave_radiation == 2 .or. flag_for_subcolumn_cloud_approximation_for_shortwave_radiation == 2)
>
> Please revert this change.
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173932>:
>
> > @@ -4602,23 +4602,23 @@
>    type = real
>    kind = kind_phys
>  [in_nm]
> -  standard_name = in_number_concentration
> -  long_name = IN number concentration
> -  units = kg-1?
> +  standard_name = ice_nucleation_number
>
> Same as for ccpp-physics, has this change been coordinated with @grantfirl
> <https://github.com/grantfirl> and @ligiabernardet
> <https://github.com/ligiabernardet>?
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173983>:
>
> >    dimensions = (horizontal_dimension,vertical_dimension)
>    type = real
>    kind = kind_phys
>  [ccn_nm]
> -  standard_name = ccn_number_concentration
> -  long_name = CCN number concentration
> -  units = kg-1?
> +  standard_name = tendency_of_ccn_activated_number
>
> Same as for ccpp-physics, has this change been coordinated with @grantfirl
> <https://github.com/grantfirl> and @ligiabernardet
> <https://github.com/ligiabernardet>?
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497174328>:
>
> > @@ -6579,54 +6579,6 @@
>  [ccpp-arg-table]
>    name = GFS_interstitial_type
>    type = ddt
> -[qv_r]
>
> Please revert the changes between lines 6582 and 6629.
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497174570>:
>
> > @@ -6651,14 +6603,6 @@
>    type = real
>    kind = kind_phys
>    active = (flag_for_microphysics_scheme == flag_for_fer_hires_microphysics_scheme)
> -[cwm]
>
> Please revert this change.
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497174770>:
>
> > @@ -7619,7 +7563,7 @@
>    dimensions = (horizontal_dimension)
>    type = real
>    kind = kind_phys
> -[fscav]
> +[fscav_cs]
>
> Please revert this change.
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497174869>:
>
> > @@ -9218,15 +9162,15 @@
>    units = none
>    dimensions = ()
>    type = integer
> -[cldtausw]
> +[pcldtausw]
>
> Please revert this change.
> ------------------------------
>
> In gfsphysics/GFS_layer/GFS_typedefs.meta
> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497174928>:
>
> >    standard_name = RRTMGP_cloud_optical_depth_layers_at_0_55mu_band
>    long_name = approx .55mu band layer cloud optical depth
>    units = none
>    dimensions = (horizontal_dimension,vertical_dimension)
>    type = real
>    kind = kind_phys
>    optional = F
> -[cldtaulw]
> +[pcldtaulw]
>
> Please revert this change.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/fv3atm/pull/170#pullrequestreview-499008796>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG7TW2QM3UJUCWYCN4QMW7TSIJ3EPANCNFSM4RFJCK6A>
> .
>

2020-09-30 15:55 UTC, mzhangw commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +[pcldtaulw]
cldtaulw is double defined.

2020-09-30 15:55 UTC, mzhangw commented on gfsphysics/GFS_layer/GFS_typedefs.meta
> +[pcldtausw]
cldtausw is double defined

2020-10-01 15:30 UTC, mzhangw commented
I reverted changes per request. It passed all RTs and is ready for review.

On Wed, Sep 30, 2020 at 8:51 AM M Zhang <mzhangw@gmail.com> wrote:

> I will do it today.
>
>
> On Tue, Sep 29, 2020 at 6:24 PM Dom Heinzeller <notifications@github.com>
> wrote:
>
>> *@climbfuji* requested changes on this pull request.
>>
>> Same as for ccpp-physics, a number of changes need to be reverted, they
>> don't belong into this PR and will cause conflicts later on when merging
>> HWRF physics etc. Others are ok even though not within the scope of this PR.
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.F90
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497172129>:
>>
>> > @@ -1055,6 +1055,7 @@ real (kind=kind_phys), pointer :: prsik (:,:) => null()   !< Exner function at i
>>  !--- tracer handling
>>      character(len=32), pointer :: tracer_names(:) !< array of initialized tracers from dynamic core
>>      integer              :: ntrac           !< number of tracers
>> +    character(len=20), pointer :: fscav_aero(:)   !< aerosol scavenging factors
>>
>> As far as I can see, all changes to GFS_typedefs.F90 need to be reverted.
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497172886>:
>>
>> > @@ -2469,14 +2469,14 @@
>>    dimensions = ()
>>    type = integer
>>  [iovr_sw]
>> -  standard_name = flag_for_max_random_overlap_clouds_for_shortwave_radiation
>> -  long_name = sw: max-random overlap clouds
>> +  standard_name = flag_for_cloud_overlapping_method_for_shortwave_radiation
>>
>> Please revert this change.
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497172944>:
>>
>> >    units = flag
>>    dimensions = ()
>>    type = integer
>>  [iovr_lw]
>> -  standard_name = flag_for_max_random_overlap_clouds_for_longwave_radiation
>> -  long_name = lw: max-random overlap clouds
>> +  standard_name = flag_for_cloud_overlapping_method_for_longwave_radiation
>>
>> Please revert this change.
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173004>:
>>
>> > @@ -2487,14 +2487,14 @@
>>    dimensions = ()
>>    type = integer
>>  [isubc_sw]
>> -  standard_name = flag_for_sw_clouds_without_sub_grid_approximation
>> -  long_name = flag for sw clouds without sub-grid approximation
>> +  standard_name = flag_for_subcolumn_cloud_approximation_for_shortwave_radiation
>>
>> Please revert this change.
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173048>:
>>
>> >    units = flag
>>    dimensions = ()
>>    type = integer
>>  [isubc_lw]
>> -  standard_name = flag_for_lw_clouds_without_sub_grid_approximation
>> -  long_name = flag for lw clouds without sub-grid approximation
>> +  standard_name = flag_for_subcolumn_cloud_approximation_for_longwave_radiation
>>
>> Please revert this change.
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173242>:
>>
>> > @@ -4035,7 +4035,7 @@
>>    units = flag
>>    dimensions = (number_of_chemical_tracers)
>>    type = logical
>> -[fscav]
>> +[fscav_sas]
>>
>> Please revert this change.
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173472>:
>>
>> > @@ -4572,14 +4572,14 @@
>>    units = none
>>    dimensions = (horizontal_dimension)
>>    type = integer
>> -  active = (flag_for_lw_clouds_without_sub_grid_approximation == 2 .or. flag_for_sw_clouds_without_sub_grid_approximation == 2)
>> +  active = (flag_for_subcolumn_cloud_approximation_for_longwave_radiation == 2 .or. flag_for_subcolumn_cloud_approximation_for_shortwave_radiation == 2)
>>
>> Please revert this change.
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173505>:
>>
>> >  [icsdlw]
>>    standard_name = seed_random_numbers_lw
>>    long_name = random seeds for sub-column cloud generators lw
>>    units = none
>>    dimensions = (horizontal_dimension)
>>    type = integer
>> -  active = (flag_for_lw_clouds_without_sub_grid_approximation == 2 .or. flag_for_sw_clouds_without_sub_grid_approximation == 2)
>> +  active = (flag_for_subcolumn_cloud_approximation_for_longwave_radiation == 2 .or. flag_for_subcolumn_cloud_approximation_for_shortwave_radiation == 2)
>>
>> Please revert this change.
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173932>:
>>
>> > @@ -4602,23 +4602,23 @@
>>    type = real
>>    kind = kind_phys
>>  [in_nm]
>> -  standard_name = in_number_concentration
>> -  long_name = IN number concentration
>> -  units = kg-1?
>> +  standard_name = ice_nucleation_number
>>
>> Same as for ccpp-physics, has this change been coordinated with
>> @grantfirl <https://github.com/grantfirl> and @ligiabernardet
>> <https://github.com/ligiabernardet>?
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497173983>:
>>
>> >    dimensions = (horizontal_dimension,vertical_dimension)
>>    type = real
>>    kind = kind_phys
>>  [ccn_nm]
>> -  standard_name = ccn_number_concentration
>> -  long_name = CCN number concentration
>> -  units = kg-1?
>> +  standard_name = tendency_of_ccn_activated_number
>>
>> Same as for ccpp-physics, has this change been coordinated with
>> @grantfirl <https://github.com/grantfirl> and @ligiabernardet
>> <https://github.com/ligiabernardet>?
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497174328>:
>>
>> > @@ -6579,54 +6579,6 @@
>>  [ccpp-arg-table]
>>    name = GFS_interstitial_type
>>    type = ddt
>> -[qv_r]
>>
>> Please revert the changes between lines 6582 and 6629.
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497174570>:
>>
>> > @@ -6651,14 +6603,6 @@
>>    type = real
>>    kind = kind_phys
>>    active = (flag_for_microphysics_scheme == flag_for_fer_hires_microphysics_scheme)
>> -[cwm]
>>
>> Please revert this change.
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497174770>:
>>
>> > @@ -7619,7 +7563,7 @@
>>    dimensions = (horizontal_dimension)
>>    type = real
>>    kind = kind_phys
>> -[fscav]
>> +[fscav_cs]
>>
>> Please revert this change.
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497174869>:
>>
>> > @@ -9218,15 +9162,15 @@
>>    units = none
>>    dimensions = ()
>>    type = integer
>> -[cldtausw]
>> +[pcldtausw]
>>
>> Please revert this change.
>> ------------------------------
>>
>> In gfsphysics/GFS_layer/GFS_typedefs.meta
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#discussion_r497174928>:
>>
>> >    standard_name = RRTMGP_cloud_optical_depth_layers_at_0_55mu_band
>>    long_name = approx .55mu band layer cloud optical depth
>>    units = none
>>    dimensions = (horizontal_dimension,vertical_dimension)
>>    type = real
>>    kind = kind_phys
>>    optional = F
>> -[cldtaulw]
>> +[pcldtaulw]
>>
>> Please revert this change.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/NOAA-EMC/fv3atm/pull/170#pullrequestreview-499008796>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscri [...]

2020-10-06 21:32 UTC, climbfuji commented
This PR was pulled into https://github.com/NCAR/fv3atm/pull/64, which merges the changes into NCAR's feature/transition-to-capgen-1 branch. These changes will come to develop in the next couple of weeks.

2020-12-04 14:41 UTC, climbfuji commented
All changes from this PR were included in #186.

2020-12-04 14:41 UTC, closed without merging