Infrastructure improvements for radiation
NOAA-EMC/ufsatm pull request #193
Opened 2020-11-02 22:11 UTC by dustinswales

This PR contains changes to accommodate improvements to both the RRTMG and RRTMGP radiation schemes.
The changes are described in the physics PR: https://github.com/NCAR/ccpp-physics/pull/514

These changes were tested on Hera using Intel compilers. Existing RT's for the G scheme passed. New baselines for the GP RT's need to be created, for both v15p2 and

2020-11-06 17:34 UTC, climbfuji commented
The PR description is incomplete, can that be fixed please?

Also, associated PRs:

https://github.com/NCAR/ccpp-physics/pull/514
https://github.com/NOAA-EMC/fv3atm/pull/193
https://github.com/ufs-community/ufs-weather-model/pull/262

For regression testing information, see https://github.com/ufs-community/ufs-weather-model/pull/262

2020-11-06 17:41 UTC, climbfuji requested changes
Straightforward!

Please update `.gitmodules` temporarily to point to your ccpp-physics fork and your branch master-ncar-f3e6761? Thanks.

2020-11-12 23:59 UTC, climbfuji approved these changes

2020-11-13 00:13 UTC, DusanJovic-NOAA approved these changes

2020-11-13 00:23 UTC, junwang-noaa approved these changes

2020-11-13 15:20 UTC, climbfuji commented
Submodule pointer for ccpp-physics is correct, this can be merged.

2020-11-13 16:27 UTC, merged