Develop emc 3bd9665
NOAA-EMC/ufsatm pull request #208
Opened 2020-12-08 22:48 UTC by dustinswales

## Description
This PR contains an accumulation of changes to the coupling of the RRTMGP radiation and the cloud-microphysics.
-) New coupling of RRTMGP to Thompson MP
-) Include scattering in LW all-sky rte calculation (doGP_lwscat = .true.)
-) Use of internal RRTMGP cloud-optics (doGP_cldoptics_LUT or doGP_cldoptics_PADE = .true).
-) Adjust surface upwelling LW surface fluxes between RRTMGP calls using the Jacobian of the upwelling LW flux (use_LW_jacobian = .true.). F_adj = F_o + dT*Jacobian
-) Bug fix in RRTMGP interstitial data

## Testing
Answers to the v16beta baselines using RRTMGP need to be updated. The bug fix in the interstitial data greatly reduces differences between RRTMGP and RRTMG forecasts. Baselines need to be created for the new SDF.

These changes were tested using Intel on Hera. 

## Dependencies
https://github.com/NCAR/ccpp-physics/pull/528

2020-12-10 22:59 UTC, climbfuji commented
@dustinswales please update the title of this PR when you get a chance - thank you!

2020-12-16 21:23 UTC, climbfuji requested changes

2020-12-16 21:23 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.F90
> +
Don't need these whitespaces

2020-12-16 21:23 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.F90
> +    Interstitial%tsfc_ocean      = huge
Don't need these whitespaces

2020-12-16 21:23 UTC, climbfuji commented on gfsphysics/GFS_layer/GFS_typedefs.F90
> +    write (0,*) 'sum(Interstitial%tsfc_ocean      ) = ', sum(Interstitial%tsfc_ocean      )
Don't need these whitespaces

2020-12-16 21:38 UTC, climbfuji commented
@dustinswales I hate to bug you, but this PR is still pointing to hash ea5e44fcc691c9a5fedcb96f13e0ca85259c7844 of ccpp-physics, and not 37313e512087fc47f51bf12375e724c80fa3c18c. Can you fix that, please, and then update fv3atm in ufs-weather-model (I know, what a hassle every time).

2020-12-17 16:53 UTC, DusanJovic-NOAA approved these changes

2020-12-17 16:56 UTC, climbfuji approved these changes

2020-12-17 17:40 UTC, junwang-noaa approved these changes

2020-12-17 17:41 UTC, merged