Updates from v2.0.0
NOAA-EMC/ufsatm pull request #280
Opened 2021-04-14 21:55 UTC by llpcarson

## Description

Documentation updates from the ufs-weather-model release v2.0.0
Add the RRFS_v1alpha CCPP SDF
No answer changes expected  

### Issue(s) addressed

- fixes https://github.com/ufs-community/ufs-weather-model/issues/468
- fixes https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/issues/81

## Testing

Regression tests are running now, no baseline changes expected, the new test for RRFS_v1alpha will need a new baseline

## Dependencies

https://github.com/NOAA-GFDL/GFDL_atmos_cubed_sphere/pull/94

2021-04-20 13:46 UTC, DusanJovic-NOAA approved these changes

2021-04-20 14:25 UTC, junwang-noaa commented on .gitmodules
> +	url = https://github.com/llpcarson/GFDL_atmos_cubed_sphere
You can point back to GFDL dev/emc now.

2021-04-20 14:26 UTC, junwang-noaa approved these changes

2021-04-20 14:54 UTC, llpcarson commented on .gitmodules
> +	url = https://github.com/llpcarson/GFDL_atmos_cubed_sphere
Done!

2021-04-24 01:56 UTC, climbfuji commented on ccpp/suites/suite_FV3_RRFS_v1alpha.xml
> +<suite name="FV3_RRFS_v1alpha" lib="ccppphys" ver="5">
@llpcarson when you update the submodule pointer for ccpp-physics and revert `.gitmodules`, please change
```
lib="ccppphys" ver="5"
```
to
```
version="1"
```
to match the new syntax in develop. This has no impact on the tests whatsoever, therefore no need to rerun the tests, but it needs to be consistent for the future (`capgen`).

2021-04-26 02:33 UTC, climbfuji commented
@llpcarson ccpp-physics was merged, the new hash for ncar master is https://github.com/NCAR/ccpp-physics/commit/b578157c4b70c7288f578d77e1b65a02961842a1. Please address https://github.com/NOAA-EMC/fv3atm/pull/280#discussion_r619564545 when you update the submodule pointer and revert `.gitmodules`. Thanks!

2021-04-26 14:18 UTC, DusanJovic-NOAA commented
Is this PR ready for merge? @climbfuji please confirm.

2021-04-26 16:06 UTC, climbfuji requested changes

2021-04-26 16:06 UTC, climbfuji commented on ccpp/suites/suite_FV3_RRFS_v1alpha.xml
> +<suite name="FV3_RRFS_v1alpha" lib="ccppphys" ver="1">
This line is not correct. Please replace `lib="ccppphys" ver="1"` with just `version="1"` - see other SDFs.

2021-04-26 16:12 UTC, climbfuji approved these changes
Ready to merge

2021-04-26 17:07 UTC, merged