Update EMC dev/emc from NCAR dtc/develop 2019/12/17
NOAA-EMC/ufsatm pull request #30
Opened 2019-12-18 15:17 UTC by climbfuji

PLACEHOLDER

2020-01-07 17:06 UTC, HelinWei-NOAA requested changes
Since both Noah MP and RUC use the same variables for different precipitation types, we should save them for restart for both models. So in GFS_restart.F90, we need to add the case for Noah MP. For example,

! RUC 
    if (Model%lsm == Model%lsm_ruc) then
      Restart%num2d = Restart%num2d + 5
    endif

Changed to

! RUC and Noah MP
    if (Model%lsm == Model%lsm_ruc. or. Model%lsm == Model%lsm_noahmp) then
      Restart%num2d = Restart%num2d + 5
    endif

2020-01-07 17:37 UTC, HelinWei-NOAA commented
For all those extra variables added to DDT sfcprop, we didn't add how to cold-start them in FV3GFS_io.F90. Also for NoahMP, we may not need to have both precip amount and precip rate, we can convert them inside land surface driver. In this way the structure looks more like RUC.

2020-01-07 17:42 UTC, HelinWei-NOAA commented
There is another issue with Noah MP. I am not sure if we should fix with this commit or later. 
If Noah MP is running without any microphysics scheme, there will be no any precip forcing. In this case we have to use the total precip and partition it into rain or snow based on temperature.

2020-01-07 17:44 UTC, climbfuji commented
> For all those extra variables added to DDT sfcprop, we didn't add how to cold-start them in FV3GFS_io.F90. Also for NoahMP, we may not need to have both precip amount and precip rate, we can convert them inside land surface driver. In this way the structure looks more like RUC.

Understand. Enabling b4b identical restart runs for NoahMP is not in the scope of this PR, neither is rewriting the logic inside NoahMP. We only wanted to fix the bug that caused using zero precipitation rates at fhzero intervals. If there is an opportunity to streamline the logic used by both RUC LSM and NoahMP that also avoids writing 10 instead of 5 2d arrays to the restart files for b4b identical restart runs using NoahMP, then this will make life a lot easier in the future. But I think this work should be done by your team (we will be there to help with the CCPP part if needed) in a follow-up change.

2020-01-07 17:47 UTC, climbfuji commented
> There is another issue with Noah MP. I am not sure if we should fix with this commit or later.
> If Noah MP is running without any microphysics scheme, there will be no any precip forcing. In this case we have to use the total precip and partition it into rain or snow based on temperature.

Good point, I think this should go together with the work that you described just before regarding streamlining the logic used for NoahMP and RUC.

2020-01-09 03:03 UTC, HelinWei-NOAA commented
Dom, with the current modification, running fv3gfs with noah mp option can't be restarted properly. So we may use the easy fix for Noah MP precip forcing bug suggested by Moorthi: 

comment out the following lines in subroutine diag_phys_zero
    Diag%rain       = zero
    Diag%rainc      = zero
    Diag%ice        = zero
    Diag%snow       = zero
    Diag%graupel    = zero

These five fields are not accumulated and no need zero out in diagnostic bucket.

2020-01-09 03:10 UTC, climbfuji commented
> Dom, with the current modification, running fv3gfs with noah mp option can't be restarted properly. So we may use the easy fix for Noah MP precip forcing bug suggested by Moorthi:
> 
> comment out the following lines in subroutine diag_phys_zero
> Diag%rain = zero
> Diag%rainc = zero
> Diag%ice = zero
> Diag%snow = zero
> Diag%graupel = zero
> 
> These five fields are not accumulated and no need zero out in diagnostic bucket.

I would like @grantfirl's opinion on this one as well. I believe that without/before our modifications, NoahMP couldn't be restarted properly as well? Is it the purpose of this PR to fix it?

2020-01-09 03:25 UTC, HelinWei-NOAA commented
Dom,

Before your modification, Noah MP can be restarted properly because those
five precip variables in DDT Diag are stored in restart files. After your
modification, Noah MP will use the data from DDT Sfcprop. However they are
not stored in restart file for Noah MP.

Helin

On Wed, Jan 8, 2020 at 10:10 PM Dom Heinzeller <notifications@github.com>
wrote:

> Dom, with the current modification, running fv3gfs with noah mp option
> can't be restarted properly. So we may use the easy fix for Noah MP precip
> forcing bug suggested by Moorthi:
>
> comment out the following lines in subroutine diag_phys_zero
> Diag%rain = zero
> Diag%rainc = zero
> Diag%ice = zero
> Diag%snow = zero
> Diag%graupel = zero
>
> These five fields are not accumulated and no need zero out in diagnostic
> bucket.
>
> I would like @grantfirl <https://github.com/grantfirl>'s opinion on this
> one as well. I believe that without/before our modifications, NoahMP
> couldn't be restarted properly as well? Is it the purpose of this PR to fix
> it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/fv3atm/pull/30?email_source=notifications&email_token=ALPHKYAFKBIDYP2KJLVIFV3Q42IS7A5CNFSM4J4MTIYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIOY62A#issuecomment-572362600>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALPHKYBLT66TEGRWFMAT2SLQ42IS7ANCNFSM4J4MTIYA>
> .
>

2020-01-09 03:43 UTC, climbfuji commented
> Dom, Before your modification, Noah MP can be restarted properly because those five precip variables in DDT Diag are stored in restart files. After your modification, Noah MP will use the data from DDT Sfcprop. However they are not stored in restart file for Noah MP. Helin
> […](#)

I am sorry but I am confused. Where are the five diag variables written to the restart files? If you check GFS_restart.F90, then you see that the five variables that were previously in Tbd and now in Sfcprop are written to the restart files. I checked FV3GFS_io.F90 and GFS_restart.F90, and I don't see any place where IntDiag fields are written to restart files. I also checked the restart output in the EMC baseline for the NoahMP test, `/scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/trunk-20191127/fv3_gfdlmprad_noahmp/RESTART`. I don't see any file containing those five precipitation fields. I must be missing something. Can you please point me to the lines of code that are writing these IntDiag fields to disk in the current develop branch of fv3atm? Thanks!

2020-01-09 04:17 UTC, HelinWei-NOAA commented
I think you are right. We have the restarting issue for Noah MP before and
after your modifications. Noah MP with FV3GFS still has some other issues
need to be fixed. Therefore we should have another PR exclusively to
address all remaining issues for Noah MP. I will recommend Jun to go ahead
and commit your changes. Thanks.

On Wed, Jan 8, 2020 at 10:43 PM Dom Heinzeller <notifications@github.com>
wrote:

> Dom, Before your modification, Noah MP can be restarted properly because
> those five precip variables in DDT Diag are stored in restart files. After
> your modification, Noah MP will use the data from DDT Sfcprop. However they
> are not stored in restart file for Noah MP. Helin
> … <#m_-5465603627119123655_>
>
> I am sorry but I am confused. Where are the five diag variables written to
> the restart files? If you check GFS_restart.F90, then you see that the five
> variables that were previously in Tbd and now in Sfcprop are written to the
> restart files. I checked FV3GFS_io.F90 and GFS_restart.F90, and I don't see
> any place where IntDiag fields are written to restart files. I also checked
> the restart output in the EMC baseline for the NoahMP test,
> /scratch1/NCEPDEV/nems/emc.nemspara/RT/NEMSfv3gfs/trunk-20191127/fv3_gfdlmprad_noahmp/RESTART.
> I don't see any file containing those five precipitation fields. I must be
> missing something. Can you please point me to the lines of code that are
> writing these IntDiag fields to disk in the current develop branch of
> fv3atm? Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/fv3atm/pull/30?email_source=notifications&email_token=ALPHKYFECV2SAJPTGF3ZR7DQ42MOJA5CNFSM4J4MTIYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIO22KQ#issuecomment-572370218>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALPHKYDPLMY5BS4EFWNTNTLQ42MOJANCNFSM4J4MTIYA>
> .
>

2020-01-09 04:28 UTC, climbfuji commented
Thanks for checking, Helin. It's always good to have more eyes looking at the code.

2020-01-09 14:22 UTC, HelinWei-NOAA approved these changes

2020-01-09 18:41 UTC, Qingfu-Liu commented
I only go through two directories which are physics related, and compared the contents between Dom's fork and the current UFS repository. The directories are:
ufs-weather-model-DOM/FV3/gfsphysics
ufs-weather-model-DOM/FV3/ccpp
There are few changes in the IPD driver and its related physics schemes. All the changes look fine to me. The major changes are CCPP related. There are several new schemes (new suites) in Dom's fork. These new schemes (new suites) can only be called using CCPP, not IPD. In Dom's fork, some of the post_runs are merged into GFS_GWD_generic_post, so developers need to update their SDF if they have not committed their suite to the CCPP repository. All the changes look fine to me, but I can't say much to the changes of the physics schemes which I am not familiar with (for example, sfc_drv_ruc.F90). Since all the regression tests are successful,  I think it is fine to merge Dom's fork to the EMC repository.

2020-01-09 19:08 UTC, SMoorthi-emc commented on gfsphysics/GFS_layer/GFS_physics_driver.F90
> +!## CCPP ##* This code not yet in CCPP Note: Likely belongs in rascnv_pre.
I have moved this calculation inside RAS itself.  There is no need for rascnv_pre

2020-01-09 19:09 UTC, SMoorthi-emc commented on gfsphysics/GFS_layer/GFS_physics_driver.F90
>              call rascnv (im, ix, levs, dtp, dtf, Tbd%rann, Stateout%gt0,     &
it is now in my ccpp fork.

2020-01-09 19:24 UTC, Qingfu-Liu approved these changes
I only go through two directories which are physics related, and compared the contents between Dom's fork and the current UFS repository. The directories are:
ufs-weather-model-DOM/FV3/gfsphysics
ufs-weather-model-DOM/FV3/ccpp
There are few changes in the IPD driver and its related physics schemes. All the changes look fine to me. The major changes are CCPP related. There are several new schemes (new suites) in Dom's fork. These new schemes (new suites) can only be called using CCPP, not through IPD driver. In Dom's fork, some of the post_runs are merged into GFS_GWD_generic_post, so developers need to update their SDF if they have not committed their suite to the CCPP repository. All the changes look fine to me, but I can't say much to the changes of the physics schemes which I am not familiar with (for example, sfc_drv_ruc.F90). Since all the regression tests are successful, I think it is fine to merge Dom's fork to the EMC repository.

2020-01-09 19:24 UTC, SMoorthi-emc approved these changes
Looks ok to me.

2020-01-09 19:50 UTC, climbfuji commented
> Looks ok to me.

Thanks, Moorthi. I suggest to update the comments in GFS_physics_driver.F90 when your RAS-CCPP work is merged. OK?

2020-01-10 13:23 UTC, junwang-noaa approved these changes
The code changes look good to me.

2020-01-10 14:03 UTC, DusanJovic-NOAA approved these changes
Approved, based on other people's reviews.

2020-01-10 14:36 UTC, merged