Changes to
NOAA-EMC/ufsatm pull request #392
Opened 2021-09-21 19:09 UTC by dustinswales

## Description
The PR contains some small changes to FV3 to accommodate recent improvements to RRTMGP in ccpp-physics.

The changes to RRTMGP are detailed here: https://github.com/NCAR/ccpp-physics/pull/733

### Issue(s) addressed
No github issues were opened.

## Testing
These changes were tested on Hera using the Intel compilers.
Not all of the errors addressed here were uncovered by the standard RTs, but rather showed up when running in the EMC workflow. I was able to replicate these errors by extending the RTs and running the tests for longer forecast times. 
Updates to the RT baselines are needed.

## Dependencies
https://github.com/NCAR/ccpp-physics/pull/733

2021-09-21 19:12 UTC, climbfuji requested changes
Submodule pointer for GFDL_atmos_cubed_sphere is not correct.

2021-09-22 18:40 UTC, climbfuji commented
Submodule pointer for GFDL_atmos_cubed_sphere still seems to be off.

2021-10-06 14:43 UTC, DusanJovic-NOAA approved these changes

2021-10-06 14:48 UTC, junwang-noaa approved these changes

2021-10-07 16:04 UTC, climbfuji commented on .gitmodules
> +  branch = main
Let's fix the missing newline please @dustinswales

2021-10-07 16:10 UTC, climbfuji approved these changes

2021-10-07 16:10 UTC, climbfuji commented
@junwang-noaa @DusanJovic-NOAA ready to merge

2021-10-07 16:43 UTC, merged