fix the output file name and diag time
NOAA-EMC/ufsatm pull request #404
Opened 2021-09-29 03:22 UTC by junwang-noaa

## Description

The output file name does not have correct time stamp when the output time is not a integer. E.g. output_fh=0.25, the file name is currently atmf00.nc and sfcf00.nc. Also for random output time, the diag_time may not be updated when the output time is not multiple of fhzero. This PR contains fixes for the two issues.

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fv3atm issue [#403](https://github.com/NOAA-EMC/fv3atm/issues/403)

## Testing

How were these changes tested?  Tested on hera. 
What compilers / HPCs was it tested with?  
Are the changes covered by regression tests? (If not, why? Do new tests need to be added?)  
Have the ufs-weather-model regression test been run? On what platform?  
Yes on hera.
- Will the code updates change regression test baseline? If yes, why? Please show the baseline directory below.
- No

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names (ideally)

ufs-weather-model PR
fv3atm PR

2021-09-30 16:52 UTC, climbfuji reviewed
I don't understand the logic, especially in lines 763 to 772. Is it possible to document that code? Just a brief one liner what each of those blocks does would be great.

2021-09-30 17:05 UTC, DusanJovic-NOAA commented
Why do need all this logic with `lflname_fulltime`, why can we just switch to using the filename format that always include HH-MM-SS, which will simplify the code substantially. Scripting will be also simplified by always using the same file naming scheme, that does not change based on the value `output_fh`.

2021-09-30 17:08 UTC, junwang-noaa commented
> 
> 
> Why do need all this logic with `lflname_fulltime`, why can we just switch to using the filename format that always include HH-MM-SS, which will simplify the code substantially. Scripting will be also simplified by always using the same file naming scheme, that does not change based on the value `output_fh`.

This is backward compatible. Otherwise all the downstream jobs will be broken.

2021-09-30 17:16 UTC, DusanJovic-NOAA commented
> > Why do need all this logic with `lflname_fulltime`, why can we just switch to using the filename format that always include HH-MM-SS, which will simplify the code substantially. Scripting will be also simplified by always using the same file naming scheme, that does not change based on the value `output_fh`.
> 
> This is for backward compatible. Otherwise all the downstream jobs will be broken.

Can't we announce the change and downstream jobs can update scripts. This is after all develop branch, we should be able to make breaking changes. Are we going to keep backward compatibility forever. Every change we make in any of the config file structure or output is potential breaking change for somebody.

2021-09-30 17:37 UTC, climbfuji requested changes
Thanks for adding those comments. A few suggestions/corrections of typos, otherwise looks good.

2021-09-30 17:37 UTC, climbfuji commented on fv3_cap.F90
> +                ! output time is not integer hour, set lflname_fulltime to be ture, so the
```suggestion
                ! output time is not integer hour, set lflname_fulltime to be true, so the 
```

2021-09-30 17:37 UTC, climbfuji commented on fv3_cap.F90
> +            ! if the output time in output_fh array contains first time stamp output,
```suggestion
            ! If the output time in output_fh array contains first time stamp output,
```

2021-09-30 17:37 UTC, climbfuji commented on fv3_cap.F90
> +            ! if any of them is not integer hour, the history file names will
```suggestion
            ! If any of them is not integer hour, the history file names will
```

2021-09-30 17:37 UTC, climbfuji commented on fv3_cap.F90
> +              ! when output_startfh >0, check all the output time, if any of
```suggestion
              ! When output_startfh >0, check all the output time, if any of
```

2021-09-30 17:37 UTC, climbfuji commented on fv3_cap.F90
> +              ! them is not integer hour, set lflname_fulltime to be ture. The
```suggestion
              ! them is not integer hour, set lflname_fulltime to be true. The 
```

2021-09-30 17:40 UTC, junwang-noaa commented
@climbfuji I added some comments to explain, please check. Basically for frequency output, we will don't count the  the first time step output as it is labeled as fh000.

2021-09-30 17:41 UTC, climbfuji commented
> @climbfuji I added some comments to explain, please check. Basically for frequency output, we will don't count the the first time step output as it is labeled as fh000.

I did, please look at/accept my suggestions.

2021-09-30 17:44 UTC, junwang-noaa commented
@DusanJovic-NOAA Well, this will impact future operational implementations. As we don't know if we will have higher frequency output, I think we may need to get the downstream involved before we make the hard code change.

2021-09-30 17:58 UTC, DusanJovic-NOAA approved these changes

2021-09-30 17:59 UTC, climbfuji approved these changes

2021-10-01 14:41 UTC, DeniseWorthen approved these changes

2021-10-01 15:34 UTC, merged