clean up iovr=4 (exponential cloud overlapping method) in RRTMG
NOAA-EMC/ufsatm pull request #445
Opened 2021-12-16 23:16 UTC by mzhangw

This PR is to clean up the exponential cloud overlapping method in RRTMG, which reflects the practice of the pre-2018 operational HWRF model.

### Issue(s) addressed

- fixes  issue #1 in [#748](https://github.com/NCAR/ccpp-physics/issues/748)

## Testing

These changes were tested on Hera.
This PR will change the baseline for all regression tests using exponential cloud overlapping method (iovr=4).

## Dependencies

- waiting on (https://github.com/NCAR/ccpp-physics/pull/780)
- waiting on (https://github.com/ufs-community/ufs-weather-model/pull/963)

2021-12-16 23:57 UTC, grantfirl commented
@mzhangw This PR should have the ccpp-physics submodule pointer changed too, right?

2021-12-27 20:30 UTC, DusanJovic-NOAA approved these changes

2021-12-27 20:36 UTC, climbfuji requested changes
The submodule pointer update for ccpp-physics is missing. It needs to point to hash 61fc3c1d46d967f3cadfd1157011dd7085c8fa93 in @mzhangw's ccpp-physics branch `revert_iovr4`.

2021-12-27 20:44 UTC, climbfuji approved these changes

2021-12-28 14:03 UTC, climbfuji commented
@DusanJovic-NOAA I was able to push to @mzhangw's fv3atm branch. I reverted the `.gitmodules` change and updated the submodule pointer for ccpp-physics to hash 9a3846d. This PR is ready to merge - please check.

2021-12-28 14:06 UTC, merged